routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();

Route::get('/','HomeController@index');


Route::resource('audioprzewodnik','Language\LanguageController');


Route::resource('audio_guide','Admin\AudioGuideController');
Route::resource('audio_guide_point','Admin\AudioGuidePointController');

Route::resource('code','Admin\CodeController');
Route::resource('lang','Admin\LangController');

Route::get('/queue-add','HomeController@test');

Route::get('audio_guide/{id}', 'Admin\AudioGuideController@export')->name('audio_guide.export');

Route::get('audio_guide/{id}/open', 'Admin\AudioGuideController@open')->name('audio_guide.open');

Route::get('audio_guide/{id}/clear', 'Admin\AudioGuideController@clear')->name('audio_guide.clear');

Route::get('audio_guide_point/{id}/', 'Admin\AudioGuidePointController@mass')->name('audio_guide_point.mass');


Route::get('/queue-check', function () {
    //
});

app/Http/Controllers/Admin/LangController.php
<?php


namespace AudiotourCMS\Http\Controllers\Admin;


use AudiotourCMS\Http\Controllers\Controller;
use AudiotourCMS\Http\Models\Admin\AudioGuide;
use AudiotourCMS\Http\Models\Admin\Lang;
use Carbon\Carbon;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;

class LangController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth');
    }

    public function index()
    {
        $items = Lang::getAllRecords();
        return view('admin.lang.list')->with(['items'=>$items]);
    }

    public function create(Request $request)
    {
        return view('admin.lang.add');
    }

    public function store(Request $request)
    {
//        $items = Lang::getAllRecords();
        $store = Lang::storeRecord($request);

        foreach($request->all() as $key=>$value){
            $request->request->remove($key);
        }
        self::update($request,$store->id);

//        return view('admin.lang.list')->with(['items'=>$items]);
        return redirect(route('audio_guide.index'));
    }

    public function show($id)
    {
        $item = Lang::getRecord($id);
        return view('admin.lang.show')->with(['item'=>$item]);
//        $items = Code::getAllArchiveRecords();
//        return view('admin.code.show')->with(['items'=>$items]);
    }

    public function edit($id)
    {
//        $items = Code::getAllRecordsToArchive();
//        foreach ($items as $item){
//            DB::update("update code set visible = '0' where id = :id", ['id' => $item->id]);
//        }
//
//        return redirect(route('code.index'));
    }

    public function update(Request $request, $id)
    {
        if ($request->file('icon')) {
            $file = $request->file('icon');
            $storage = $file->store('public/lang/icons');
            $name_file = explode('/', $storage);
            $banner = '/storage/lang/icons/'. $name_file[3];
        }else{
            $banner = '';
        }

//        $items = Lang::getAllRecords();
        Lang::updateRecord($request,$id,$banner);
//        return view('admin.lang.list')->with(['items'=>$items]);
        return redirect(route('audio_guide.index'));
    }

    public function destroy($id)
    {
        Lang::destroyRecord($id);
        return redirect(route('audio_guide.index'));
    }
}

resources/views/admin/lang/add.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
	<div class="row">
		<div class="col-md-12">
			<form action="{{route('lang.store')}}" method="POST" enctype="multipart/form-data">
				{{csrf_field()}}

				<h2>Nowy język</h2>

				<hr>

				<div class="form-group row">
					<label class="col-md-2 col-form-label">Język</label>
					<div class="col-md-10">
						<input type="text" name="name" value="" class="form-control"/>
					</div>
				</div>

				<hr>
				<div class="form-group row">
					<div class="col-md-12">
						<h4 style="color: red">Ikona powinna być w wymiarach <b>177 x 134</b> w formacie <b>.png</b></h4>
					</div>

					<label class="col-md-2 col-form-label">Banner</label>
					<div class="col-md-10">
						<input type="file" name="icon"/>
						<img v-if="url" :src="url" />
					</div>
				</div>

				<hr>

				<div class="form-group row">
					<label class="col-md-2 col-form-label">Skrót (pl, en, de)</label>
					<div class="col-md-10">
						<input type="text" name="tag" value="" class="form-control"/>
					</div>
				</div>

				<hr>

				<input type="submit" value="Dodaj" class="btn btn-primary custom-btn">
			</form>
		</div>
	</div>
</div>
<script type="text/javascript">
	$('#sub_title_pl').summernote();
	$('#sub_title_cz').summernote();

	$('.data_od,.data_do').datepicker({
		dateFormat: 'yyyy-mm-dd',
		timepicker: 'hh:i'
	})

	$(document).on({
		dragover: function() {
			return false;
		},
		drop: function() {
			return false;
		}
	});
</script>
@stop

resources/views/admin/lang/list.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
<div class="row header">
	<div class="col-md-12 border-bottom" >
		<div class="col-md-12 title">
			<h2>JĘZYKI LISTA</h2>
		</div>
		<div class="col-md-12" >
			<a href="{{route('lang.create')}}" class="btn btn-primary m-b-20 custom-btn"><i class="fa fa-plus"></i> Dodaj język</a>
		</div>
	</div>
</div>
	<br>
	<br>
<div class="row">
	<div class="col-md-12">
		<ul style="list-style: none; padding: 0!important;">
			@foreach($items as $item)
				<li style="height: 15px;display: flex;">
					<img style="height: 50px;margin-top: -12px;" src="{{$item->icon}}" alt="flag">
					<p style="margin-top: 4px;" class="col-md-3">Język: <b>{{$item->name}}</b></p>

					<a style="height: 30px;margin-top: -2px;" href="{{route('lang.show',$item->id)}}" class="btn btn-primary"><i class="fa fa-edit"></i> Edytuj język</a>
					<a style="height: 30px;margin-top: -2px;" class="btn btn-danger custom-delete-btn" href="{{ route('lang.destroy',$item->id) }}" onclick="event.preventDefault(); document.getElementById('delete-form-item-{{$item->id}}').submit();"><i class="fa fa-trash-o"></i> Usuń język</a>

					<form id="delete-form-item-{{$item->id}}" action="{{ route('lang.destroy',$item->id) }}" method="POST" style="display: none;">
						<input type="hidden" name="_method" value="DELETE" />
						@csrf
					</form>
				</li>
				<hr>
			@endforeach
		</ul>
	</div>
</div>
	{{$items->links()}}
</div>
@stop

resources/views/admin/lang/show.blade.php
@extends('layouts.app')

@section('content')
	<div class="container">
		<div class="row">
			<div class="col-md-12">
				<form action="{{route('lang.update',$item->id)}}" method="POST" enctype="multipart/form-data">
					<input type="hidden" name="_method" value="PUT" />
					{{csrf_field()}}

					<h2>Edytuj język</h2>

					<hr>

					<div class="form-group row">
						<label class="col-md-2 col-form-label">Język</label>
						<div class="col-md-10">
							<input type="text" name="name" value="{{$item->name}}" class="form-control"/>
						</div>
					</div>

					<hr>
					<div class="form-group row">

						<div class="col-md-12">
							<img style="height: 50px;margin-top: -12px;" src="{{$item->icon}}" alt="flag">
							<h4 style="color: red">Ikona powinna być w wymiarach <b>177 x 134</b> w formacie <b>.png</b></h4>
						</div>

						<label class="col-md-2 col-form-label">Banner</label>
						<div class="col-md-10">
							<input type="file" name="icon"/>
							<img v-if="url" :src="url" />
						</div>
					</div>

					<hr>

					<div class="form-group row">
						<label class="col-md-2 col-form-label">Skrót (pl, en, de)</label>
						<div class="col-md-10">
							<input type="text" name="tag" value="{{$item->tag}}" class="form-control"/>
						</div>
					</div>

					<hr>

					<input type="submit" value="Dodaj" class="btn btn-primary custom-btn">
				</form>
			</div>
		</div>
	</div>
	<script type="text/javascript">
		$('#sub_title_pl').summernote();
		$('#sub_title_cz').summernote();

		$('.data_od,.data_do').datepicker({
			dateFormat: 'yyyy-mm-dd',
			timepicker: 'hh:i'
		})

		$(document).on({
			dragover: function() {
				return false;
			},
			drop: function() {
				return false;
			}
		});
	</script>
@stop