routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();

Route::get('/','HomeController@index');


Route::resource('audioprzewodnik','Language\LanguageController');


Route::resource('audio_guide','Admin\AudioGuideController');
Route::resource('audio_guide_point','Admin\AudioGuidePointController');

Route::resource('code','Admin\CodeController');
Route::resource('lang','Admin\LangController');

Route::get('/queue-add','HomeController@test');

Route::get('audio_guide/{id}', 'Admin\AudioGuideController@export')->name('audio_guide.export');

Route::get('audio_guide/{id}/open', 'Admin\AudioGuideController@open')->name('audio_guide.open');

Route::get('audio_guide/{id}/clear', 'Admin\AudioGuideController@clear')->name('audio_guide.clear');

Route::get('audio_guide_point/{id}/', 'Admin\AudioGuidePointController@mass')->name('audio_guide_point.mass');


Route::get('/queue-check', function () {
    //
});

app/Http/Controllers/Admin/AudioGuideController.php
<?php

namespace AudiotourCMS\Http\Controllers\Admin;

use AudiotourCMS\Http\Controllers\Controller;
use AudiotourCMS\Http\Models\Admin\AudioGuide;
use AudiotourCMS\Http\Models\Admin\AudioGuidePoint;
use Illuminate\Http\Request;
use AudiotourCMS\Http\Models\Admin\Lang;
use Response;

class AudioGuideController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth');
    }

    public function index()
    {
        $items = AudioGuide::getAllRecords(3, 1);
        return view('admin.audio_guide.list')->with(['items'=>$items]);
    }

    public function create()
    {
        $langs = Lang::getAllRecords();
        return view('admin.audio_guide.add')->with(['langs'=>$langs]);
    }

    public function store(Request $request)
    {
        $store = AudioGuide::storeRecord($request);

        foreach($request->all() as $key=>$value){
            $request->request->remove($key);
        }
        self::update($request,$store->id);

        return redirect(route('audio_guide.index'));
    }

    public function show($id)
    {
        $langs = Lang::getAllRecords();
        $audio_guides = AudioGuide::getRecord($id);
        return view('admin.audio_guide.show')->with(['item'=>$audio_guides,'langs'=>$langs]);
    }

    public function edit($id)
    {
        $column = array();
        array_push($column, 'ID' );
        array_push($column, 'Nazwa' );
        array_push($column, 'Kolejnosc' );
        array_push($column, 'Dodane Wideo' );
        array_push($column, 'Nadrzedne' );
        array_push($column, 'Podrzedne' );
        array_push($column, 'Wybrano' );
        array_push($column, 'Wysluchano' );


        $table = AudioGuidePoint::getPointsByID1($id);

        $handle = fopen("/var/www/gdynia/storage/app/public/audio_guide/gdynia.csv", 'w+');
//        $handle = fopen("/Applications/XAMPP/htdocs/welski/app/Http/Controllers/Admin/gdynia.csv", 'w+');


        fputcsv($handle, $column, ";",'"');

        foreach($table as $row) {
            $a = array();

            array_push($a, $row['id'] );
            array_push($a, $row['name'] );
            // array_push($a, iconv('UTF-8', 'Windows-1250', $row['name']) );
            array_push($a, $row['position'] );
            array_push($a, $row['is_video'] );
            array_push($a, $row['parent'] );
            array_push($a, $row['is_child'] );
            array_push($a, $row['is_select'] );
            array_push($a, $row['was_heard'] );

            fputcsv($handle, $a, ";",'"');
        }

        fclose($handle);

        //        //server
        return Response::download("/var/www/gdynia/storage/app/public/audio_guide/gdynia.csv", "gdynia.csv");
//        return Response::download("/Applications/XAMPP/htdocs/welski/app/Http/Controllers/Admin/gdynia.csv", "gdynia.csv");
    }

    public function open($id)
    {
        $item = AudioGuide::getRecord($id);
        return view('admin.audio_guide.export')->with(['item'=>$item]);
    }

    public function clear($id)
    {
        AudioGuidePoint::deleteAllByTrackID($id);
        $items = AudioGuide::getAllRecords(3, 1);
        return view('admin.audio_guide.list')->with(['items'=>$items]);
    }

    public function export(Request $request, $id)
    {
        if ($request->file('import_svc_file')){
            $file_path = $request->file('import_svc_file');

            $file = fopen($file_path, 'r');

            $count = 0;

            while (($line = fgetcsv($file)) !== FALSE) {    // Read one line
                $item = str_replace(' "', '', $line);
                $item2 = str_replace('" ', '', $item);
                $item3 = str_replace(null, ' ', $item2);
                $array[] = $item3;
                $count ++;
            }

            $columns = explode(';', $array[0][0]);

            $back = "http://127.0.0.1:8000/audio_guide";

            if ($request->checkbox_add && $columns[0] == "ID"){
                echo "<h4 style='color: red;' ><b>Chcesz dodać punkty ale nie usuńełęś kolumne ID</b></h4>";
                return;
            }
            if ($request->checkbox_update && $columns[0] != "ID"){
                echo "<h4 style='color: red;' ><b>Chcesz zaaktualizować punkty ale nie ma w pliku kolumny ID</b></h4>";
                return;
            }


            if ($request->checkbox_add){
                echo "<h4 style='color: red;' ><b>Dodałeś te punkty</b></h4>";
            }
            if ($request->checkbox_update){
                echo "<h4><b>Zaaktualizowałeś te punkty</b></h4>";
            }

            echo "<a style='font-size: 30px' href='$back'>Wróć</a>";

            echo "<table style='border: 1px solid black;border-collapse: collapse;width:100%;text-align: left'>";
            foreach (range(0,$count-1) as $i){
                if ($i > 0){
                    $a = explode(';', $array[$i][0]);
                    $countValue = 0;
                    echo '<tr style="border: 1px solid black;">';

                    $id_point = $a[0];
                    $data = $request->all();

                    foreach ($a as $value){

                        if($columns[$countValue] == "ID"){
                            print "<th style='padding: 7px;'> ".$columns[$countValue].": ".$value."</th>";
                        }
                        if($columns[$countValue] == "Nazwa") {
                            $strName = iconv('Windows-1250', 'UTF-8', $value);
                            print "<th> " . $columns[$countValue] . ": " . $strName . "</th>";
                            $data['name'] = $strName;
                        }
                        if($columns[$countValue] == "Kolejnosc"){
                            print "<th> ".$columns[$countValue].": ".$value."</th>";
                            $data['position'] = $value;
                        }

                        if($columns[$countValue] == "Dodane Wideo"){
                            print "<th> ".$columns[$countValue].": ".$value."</th>";
                            $data['is_video'] = $value;
                        }

                        if($columns[$countValue] == "Nadrzedne"){
                            print "<th> ".$columns[$countValue].": ".$value."</th>";
                            $data['parent'] = $value;
                        }
                        if($columns[$countValue] == "Podrzedne"){
                            print "<th> ".$columns[$countValue].": ".$value."</th>";
                            $data['is_child'] = $value;
                        }

                        $countValue++;
                    }

                    if ($request->checkbox_add){
                        $data['id_category'] = $id;

                        $store = AudioGuidePoint::create($data);

                        $update = $request->all();
                        $update['id_article'] = $store->id;
                        AudioGuidePoint::find($store->id)->update($update);
                    }
                    if ($request->checkbox_update){
                        $data['id_article'] = $id_point;
                        AudioGuidePoint::find($id_point)->update($data);
                    }

                    echo '</tr>';
                }
            }
            echo "</table>";


            $back = "http://127.0.0.1:8000/audio_guide";

            if ($request->checkbox_add){
                echo "<h4 style='color: red;' ><b>Dodałeś te punkty</b></h4>";
            }
            if ($request->checkbox_update){
                echo "<h4><b>Zaaktualizowałeś te punkty</b></h4>";
            }

            echo "<a style='font-size: 30px' href='$back'>Wróć</a>";
            fclose($file);
        }
    }

    public function update(Request $request, $id)
    {
        AudioGuide::updateRecord($request,$id);
        return redirect(route('audio_guide.index'));
    }

    public function destroy($id)
    {
        AudioGuide::destroyRecord($id);
        return redirect(route('audio_guide.index'));
    }
}

resources/views/admin/audio_guide/add-all.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row header">
            <div class="col-md-12 border-bottom">
                <div class="col-md-12 title">
                    <h2>Masowe Dodawanie zdjęć i nagrań</h2>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-12"  id="app">
                <form action="{{route('audio_guide_point.export', $audio_guide_id)}}" method="POST" enctype="multipart/form-data">

                    <input type="hidden" name="audio_guide_id" value="{{$audio_guide_id}}" />
                    {{csrf_field()}}

                    <h3 style="color: red">UWAGA! Język / Ścieżka ma {{count($points)}} punktów. o nazwach: <br> @foreach($points as $item) {{$item['position']}},@endforeach</h3>
                    <br>
                    <input type="hidden" name="size" value="{{count($points)}}" />
                    @foreach($points as $item)
                        <input type="hidden" name="pointID{{$item['position']}}" value="{{$item['id']}}" />
                    @endforeach

                    <div class="form-group row">
                        <label class="col-md-5 col-form-label">Dodaj wszystkie Zdjęcia (.jpg 480 x 640)</label>
                        <div class="col-md-7">
                            <input type="file" accept="image/jpeg" name="images_new[]" value=""  multiple/>
                        </div>
                    </div>

                    <div class="form-group row">
                        <label class="col-md-5 col-form-label">Dodaj wszystkie Nagrania (tylko .mp3)</label>
                        <div class="col-md-7">
                            <input type="file" accept="audio/mp3" name="audio_new[]" multiple/>
                        </div>
                    </div>

                    <input type="submit" value="Dodaj" class="btn btn-primary">
                </form>
            </div>
        </div>
        <hr>
        <div class="row">
            <div class="col-md-12">
                <h3 style="color: red">Zdjęcia muszą być z rozdzielczością nie wększą niż <b>480 x 640</b> w formacie .jpg</h3>
                <h3 style="color: red">Nagrania wrzucamy skompresowane z odpowiednimi parametrami tylko w <b>formacie .mp3</b></h3>
            </div>
        </div>
    </div>
    <script type="text/javascript">
        $(document).on({
            dragover: function() {
                return false;
            },
            drop: function() {
                return false;
            }
        });
    </script>
@stop

resources/views/admin/audio_guide/add.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
	<div class="row">
		<div class="col-md-12">
			<form action="{{route('audio_guide.store')}}" method="POST" enctype="multipart/form-data">
				{{csrf_field()}}

				<h2>Nowy język</h2>

				<hr>

				<div class="form-group row">
					<label class="col-md-2 col-form-label">Nazwa: </label>
					<div class="col-md-10">
						<input type="text" name="name" value="" class="form-control"/>
					</div>
				</div>

				<hr>

				<div class="form-group row" >
					<label class="col-md-2 col-form-label">Kolejność: </label>
					<div class="col-md-2">
						<select class="form-control" name="position" >
							<option value="0">-- Wybierz --</option>
							@foreach(range(1,100) as $i)
								<option value="{{$i}}">{{$i}}</option>
							@endforeach
						</select>
					</div>
				</div>
				<div class="form-group row">
					<label class="col-md-2 col-form-label">Visible: </label>
					<div class="col-md-3">
						<select class="form-control" name="visible" >
							<option value="1">Tak</option>
							<option value="0">Nie</option>
						</select>
					</div>
				</div>

				<hr>

				<div class="form-group row">
					<label class="col-md-2 col-form-label">Flaga: </label>
					<div class="col-md-3">
						<select class="form-control" name="flag" >
							<option value="0">----------------wybierz----------------</option>
							@foreach($langs as $item)
								<option value="{{$item->icon}}">{{$item->name}}</option>
							@endforeach
						</select>
					</div>
				</div>

				<hr>

				<div class="form-group row" style="display: none" >
					<label class="col-md-2 col-form-label">Data dodania</label>
					<div class="col-md-10">
						<input type="text" name="timestamp" value="{{\Carbon\Carbon::now('Europe/Paris')->toDateTimeString()}}" class="form-control"/>
					</div>
				</div>

				<input type="submit" value="Dodaj" class="btn btn-primary custom-btn">
			</form>
		</div>
	</div>
</div>
<script type="text/javascript">
	$('#summernote').summernote();

	$('.data_od,.data_do').datepicker({
		dateFormat: 'yyyy-mm-dd',
		timepicker: 'hh:i'
	})

	$(document).on({
		dragover: function() {
			return false;
		},
		drop: function() {
			return false;
		}
	});
</script>
@stop

resources/views/admin/audio_guide/list.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
<div class="row header">
	<div class="col-md-12 border-bottom" >
		<div class="col-md-12 title">
			<h2>AUDIOPRZEWODNIK - LISTA</h2>
		</div>
		<div class="col-md-12" >
			<a href="{{route('audio_guide.create')}}" class="btn btn-primary m-b-20 custom-btn"><i class="fa fa-plus"></i> Dodaj nowy język</a>
		</div>
	</div>
</div>
<br>
<br>
@foreach($items as $item)
		<div class="col-md-4 custom-app-card">
			<div class="custom-app-wrap">
				<ul style="text-align: center">
					<li><h4 style="text-align: left;">Statystyki</h4></li>
					<li><p style="text-align: left; font-size: 12px;"><b>Wybrano: </b>{{$item->is_select}}</p></li>
					<hr>
					<li><p style="text-align: left; font-size: 9px;"><b>id: </b>{{$item->id}}</p></li>
							<li><img src="{{$item->flag}}" alt="{{$item->name}}" class="show-blade-image m-b-20"/></li>
					<li><h5><b>Język: </b>{{$item->name}}</h5></li>
					<li><h5><b>Kolejność: </b>{{$item->position}}</h5></li>
					<hr>
					<a href="{{route('audio_guide.edit',$item->id)}}" class="btn btn-primary custom-edit-btn">Export</a>
					<a href="{{route('audio_guide.open',$item->id)}}" class="btn btn-primary custom-edit-btn">Import</a>
					<a href="{{route('audio_guide.clear',$item->id)}}" class="btn btn-primary custom-delete-btn">Usuń wszystko</a>
				</ul>

				<ul>
				@foreach($item->pointArray as $point)
					<li style="height: 25px;">
						<p>@if($point['is_video'] == 1) v @endif</p>
						<a href="{{route('audio_guide_point.show',$point['id'])}}" style="padding-left: 0px; @if($point['parent'] != null || $point['parent'] != 0 ) margin-left: 10px; @endif"   class="col-md-9"> <span style="color: red">{{$point['position']}}||</span> @if($point['is_child'] == 1) &#8595 @endif  @if($point['parent'] != null || $point['parent'] != 0 ) {{$point['parent']}} &#8594 @endif {{$point['id']}}. @if(strlen($point['name']) > 30) {{mb_substr($point['name'], 0, 20)}} ... @else {{$point['name']}} @endif</a>
						<a href="{{route('audio_guide_point.show',$point['id'])}}" style="padding-left: 0px"class="col-md-1"><i  class="fa fa-edit "></i> </a>
						<a href="{{ route('audio_guide_point.destroy',$point['id']) }}" onclick="event.preventDefault(); document.getElementById('delete-form-{{$point['id']}}').submit();" class="col-md-1" style="padding-left: 0px"><i style="color:red" class="fa fa-trash "></i> </a>
						<form id="delete-form-{{$point['id']}}" action="{{ route('audio_guide_point.destroy',$point['id']) }}" method="POST" style="display: none;">
							<input type="hidden" name="_method" value="DELETE" />
							@csrf
						</form>
					</li>
				@endforeach
					<li style="margin-top: 10px"><a href="{{route('audio_guide_point.create', ['about_park_id'=>$item->id])}}" class="btn btn-primary m-b-20 custom-btn"><i class="fa fa-plus"></i> Dodaj nowy punkt</a></li>
					<li style="margin-top: 10px"><a href="{{route('audio_guide_point.edit', $item->id)}}" class="btn btn-primary m-b-20 custom-btn"><i class="fa fa-plus"></i> Dodaj masowo</a></li>
				</ul>

				<hr>

				<ul style="display: contents;">
					<a href="{{route('audio_guide.show',$item->id)}}" class="btn btn-primary custom-edit-btn"><i class="fa fa-edit"></i> Edytuj język</a>
					<a class="btn btn-danger custom-delete-btn" href="{{ route('audio_guide.destroy',$item->id) }}" onclick="event.preventDefault(); document.getElementById('delete-form-item-{{$item->id}}').submit();"><i class="fa fa-trash-o"></i> Usuń język</a>

					<form id="delete-form-item-{{$item->id}}" action="{{ route('audio_guide.destroy',$item->id) }}" method="POST" style="display: none;">
						<input type="hidden" name="_method" value="DELETE" />
						@csrf
					</form>
				</ul>

			</div>
		</div>
@endforeach
{{$items->links()}}
</div>
@stop

resources/views/admin/audio_guide/point-add.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
<div class="row">
<div class="col-md-12"  id="app">
<form action="{{route('audio_guide_point.store')}}" method="POST" enctype="multipart/form-data">

<input type="hidden" name="audio_guide_id" value="{{$lang->id}}" />
{{csrf_field()}}

	<h2>Nowy punkt. Język: {{$lang->name}}</h2>

	<hr>

	<div class="form-group row">
		<label class="col-md-2 col-form-label">Nazwa: </label>
		<div class="col-md-10">
			<input type="text" name="name" value="" class="form-control"/>
		</div>
	</div>

	<hr>

	<div class="form-group row" >
		<label class="col-md-2 col-form-label">Kolejność: </label>
		<div class="col-md-2">
			<select class="form-control" name="position" >
				@foreach(range(0,500) as $i)
					<option value="{{$i}}">{{$i}}</option>
				@endforeach
			</select>
		</div>
	</div>

	<div class="form-group row">
		<label class="col-md-2 col-form-label">Visible: </label>
		<div class="col-md-3">
			<select class="form-control" name="visible" >
				<option value="1">Tak</option>
				<option value="0">Nie</option>
			</select>
		</div>
	</div>

	<hr>

	<div class="form-group row">
		<div class="col-md-12">
			<h4 style="color: red">Zdjęcia muszą być z rozdzielczością nie wększą niż <b>480 x 640</b> w formacie <b>.jpg</b></h4>
		</div>

		<label class="col-md-2 col-form-label">Banner</label>
		<div class="col-md-10">
			<input type="file" name="banner"/>
			<img v-if="url" :src="url" />
		</div>
	</div>

	<hr>

	<div class="form-group row">
		<div class="col-md-12">
			<h4 style="color: red">Pliki audio w formacie <b>.mp3</b></h4>
		</div>

		<label class="col-md-2 col-form-label">Audio Plik</label>
		<div class="col-md-10">
			<input type="file" accept="audio/mp3" name="audio_file" />
		</div>
	</div>

	<hr>
	<div class="form-group row">
		<div class="col-md-12">
			<h4 style="color: red">Pliki video w formacie <b>.mp4</b></h4>
		</div>

		<label class="col-md-2 col-form-label">Video Plik</label>
		<div class="col-md-10">
			<input type="file" name="video_file"/>
		</div>
	</div>
	<div class="form-group row" >
		<label class="col-md-2 col-form-label">Odtwarzaj video: </label>
		<div class="col-md-2">
			<select class="form-control" name="is_video" >
				<option value="0">Nie</option>
				<option value="1">Tak</option>
			</select>
		</div>
	</div>
	<hr>


	<div class="form-group row" >
		<label class="col-md-2 col-form-label">Czy ma w sobie punkty pozszezone: </label>
		<div class="col-md-2">
			<select class="form-control" name="is_child" >
				<option value="0">Nie</option>
				<option value="1">Tak</option>
			</select>
		</div>
	</div>
	<div class="form-group row" >
		<label class="col-md-2 col-form-label">Punkt nadrzędny: </label>
		<div class="col-md-2">
			<select class="form-control" name="parent" >
				<option value="">-- Wybierz--</option>
				@foreach($points as $item)
					@if($item['is_child'] == "1")
						<option value="{{$item['id']}}">{{$item['name']}}</option>@endif
				@endforeach
			</select>
		</div>
	</div>

	<hr>

	<input type="submit" value="Dodaj" class="btn btn-primary custom-btn">
</form>



</div>
</div>
</div>
<script type="application/javascript">
	$(document).on({
		dragover: function() {
			return false;
		},
		drop: function() {
			return false;
		}
	});

</script>
@stop

resources/views/admin/audio_guide/point-show.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
<div class="row">
<div class="col-md-12">
<form action="{{route('audio_guide_point.update',$item->id)}}" method="POST" enctype="multipart/form-data">
<input type="hidden" name="_method" value="PUT" />

<input type="hidden" name="id_category" value="{{$item->id_category}}" />
{{csrf_field()}}

	<h3>Statystyki</h3>
	<h4>Wybrano: {{$item->is_select}}</h4>
	<h4>Wysłuchano: {{$item->was_heard}}</h4>

	<hr>

	<h2>Edytuj: {{$item->name}}</h2>


	<hr>

	<div class="form-group row">
		<label class="col-md-2 col-form-label">Nazwa: </label>
		<div class="col-md-10">
			<input type="text" name="name" value="{{$item->name}}" class="form-control"/>
		</div>
	</div>

	<hr>

	<div class="form-group row" >
		<label class="col-md-2 col-form-label">Kolejność: </label>
		<div class="col-md-2">
			<select class="form-control" name="position" >
				<option value="0">-- Wybierz --</option>
				@foreach(range(0,100) as $i)
					<option value="{{$i}}" @if($i == $item->position) selected @else @endif>{{$i}}</option>
				@endforeach
			</select>
		</div>
	</div>

	<div class="form-group row">
		<label class="col-md-2 col-form-label">Visible: </label>
		<div class="col-md-3">
			<select class="form-control" name="visible" >
				<option value="1" @if($item->visible == 1) selected @endif>Tak</option>
				<option value="0" @if($item->visible == 0) selected @endif>Nie</option>
			</select>
		</div>
	</div>

	<hr>

	<div class="form-group row">
		<div class="col-md-12">
			<h4 style="color: red">Zdjęcia muszą być z rozdzielczością nie wększą niż <b>480 x 640</b> w formacie <b>.jpg</b></h4>
		</div>

		<label class="col-md-2 col-form-label">Banner</label>
		<div class="col-md-10">
			<input type="file" name="banner"/>
			<img v-if="url" :src="url" />
			@if($item->banner != null)
				<img src="{{$item->banner}}" alt="{{$item->name}}">
			@endif
		</div>
	</div>

	<hr>

	<div class="form-group row">
		<div class="col-md-12">
			<h4 style="color: red">Pliki audio w formacie <b>.mp3</b></h4>
		</div>

		<label class="col-md-2 col-form-label">Audio Plik</label>
		<div class="col-md-10">
			<input type="file" accept="audio/mp3" name="audio_file" />
			@if($item->audio_file != null)
				<audio controls>
					<source src="{{$item->audio_file}}" type="audio/ogg">
					<source src="{{$item->audio_file}}" type="audio/mpeg">
				Your browser does not support the audio element.
				</audio>
			@endif
		</div>
	</div>

	<hr>
	<div class="form-group row">
		<div class="col-md-12">
			<h4 style="color: red">Pliki video w formacie <b>.mp4</b></h4>
		</div>

		<label class="col-md-2 col-form-label">Video Plik</label>
		<div class="col-md-10">
			<input type="file" name="video_file"/>
			@if($item->video_file != null)
				<video width="320" height="240" controls>
					<source src="{{$item->video_file}}" type="video/mp4">
					<source src="{{$item->video_file}}" type="video/ogg">
					Your browser does not support the video tag.
				</video>
			@endif
		</div>
	</div>
	<div class="form-group row" >
		<label class="col-md-2 col-form-label">Odtwarzaj video: </label>
		<div class="col-md-2">
			<select class="form-control" name="is_video" >
				<option value="0" @if($item->is_video == "0") selected @else @endif>Nie</option>
				<option value="1" @if($item->is_video == "1") selected @else @endif>Tak</option>
			</select>
		</div>
	</div>
	<hr>

	<div class="form-group row" >
		<label class="col-md-2 col-form-label">Czy ma w sobie punkty pozszezone: </label>
		<div class="col-md-2">
			<select class="form-control" name="is_child" >
				<option value="0" @if($item->is_child == "0") selected @else @endif>Nie</option>
				<option value="1" @if($item->is_child == "1") selected @else @endif>Tak</option>
			</select>
		</div>
	</div>

	<div class="form-group row" >
		<label class="col-md-2 col-form-label">Punkt nadrzędny: </label>
		<div class="col-md-2">
			<select class="form-control" name="parent" >
				<option value="">-- Wybierz --</option>
				@foreach($points as $point)
					@if($point['is_child'] == "1")
						<option value="{{$point['id']}}" @if($item->parent == $point['id']) selected @else @endif>{{$point['name']}}</option>
					@endif
				@endforeach
			</select>
		</div>
	</div>

	<hr>
	<input type="submit" value="Zapisz" class="btn btn-primary custom-btn">
</form>
</div>
</div>
</div>
        <script type="text/javascript">
			$('#desc_pl').summernote();
			$('#desc_en').summernote();
			$('#desc_de').summernote();

		   $('.data_od,.data_do').datepicker({
				dateFormat: 'yyyy-mm-dd',
				timepicker: 'hh:i'
			})

        </script>
@stop

resources/views/admin/audio_guide/show.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
<div class="row">
<div class="col-md-12">
<form action="{{route('audio_guide.update',$item->id)}}" method="POST" enctype="multipart/form-data">
<input type="hidden" name="_method" value="PUT" />
{{csrf_field()}}


	<h2>Edytuj: {{$item->name}}</h2>

	<hr>

	<div class="form-group row">
		<label class="col-md-2 col-form-label">Nazwa: </label>
		<div class="col-md-10">
			<input type="text" name="name" value="{{$item->name}}" class="form-control"/>
		</div>
	</div>

	<hr>

	<div class="form-group row" >
		<label class="col-md-2 col-form-label">Kolejność</label>
		<div class="col-md-2">
			<select class="form-control" name="position" >
				@foreach(range(1,100) as $i)
					<option value="{{$i}}" @if($i == $item->position) selected @else @endif>{{$i}}</option>
				@endforeach
			</select>
		</div>
	</div>

	<div class="form-group row">
		<label class="col-md-2 col-form-label">Visible: </label>
		<div class="col-md-3">
			<select class="form-control" name="visible" >
				<option value="1" @if($item->visible == 1) selected @endif>Tak</option>
				<option value="0" @if($item->visible == 0) selected @endif>Nie</option>
			</select>
		</div>
	</div>

	<hr>

	<div class="form-group row">
		<label class="col-md-2 col-form-label">Flaga: </label>
		<div class="col-md-3">
			<select class="form-control" name="flag" >
				<option value="0">----------------wybierz----------------</option>
				@foreach($langs as $lang)
					<option @if($item->flag == $lang->icon) selected @else  @endif value="{{$lang->icon}}">{{$lang->name}}</option>
				@endforeach
			</select>
		</div>
	</div>

	<hr>

	<div class="form-group row" style="display: none" >
		<label class="col-md-3 col-form-label">Data dodania</label>
		<div class="col-md-9">
			<input type="text" name="timestamp" value="{{\Carbon\Carbon::now('Europe/Paris')->toDateTimeString()}}" class="form-control"/>
		</div>
	</div>

	<input type="submit" value="Zapisz" class="btn btn-primary custom-btn">
</form>
</div>
</div>
</div>
        <script type="text/javascript">
           $('#summernote').summernote();

		   $('.data_od,.data_do').datepicker({
				dateFormat: 'yyyy-mm-dd',
				timepicker: 'hh:i'
			})
		   $(document).on({
			   dragover: function() {
				   return false;
			   },
			   drop: function() {
				   return false;
			   }
		   });
        </script>
@stop